### ISSUE TITLE
Clocks DO NOT WORK properly

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#17]

**Comment by Khagrin2** [comment]
Subsequent to the CCC4 Bonus Stockfish Lc0 (net 32890) event, the clocks started displaying odd behaviour.   Subjectively it appears that there is a large increment being used, but that is not the case.  Player One's clock gets a big bump when it moves and Player Two's clock starts running.  When Player Two moves, Player One's clock drops back down immediately.  The same problem for Player Two's clock, i.e. symmetrical issue.  I noticed that the "Time" graph does not show "time used" as is typically the case (though I haven't looked at that graph for a bit).  Perhaps devs made changes to the format of that graph (which now tries to show just declining times from initial time control) and mucked things up.  

This is a severe issue that needs to be addressed before any CCC5 event begins.

**Comment by coolchess123** [comment]
I am closing all issues now, so that we know what new issues to track
