### ISSUE TITLE
Layout gets broken when ads are on.

### ISSUE THREAD

**Issue by mooskagh** [coolchess123/CCC-feedback#18]
That  happens not every time, but regularly (daily or so).
Reproducible on all my computers. (Various OSes, but Chrome everywhere).

Ads are just added at the bottom rather than replace upper-top corner.

![image](https://user-images.githubusercontent.com/11266455/52301039-bd052480-2989-11e9-9841-2fb47df1c08d.png)

**Comment by mooskagh** [comment]
That had been happening since forever btw, but today for some reason it's reproducible every single time.

**Comment by coolchess123** [comment]
I am closing all issues now, so that we know what new issues to track
