### ISSUE TITLE
CCCC page crashes after 4-5 hours

### ISSUE THREAD

**Issue by mooskagh** [coolchess123/CCC-feedback#19]
Happens on all computers that I have
(Linux/Windows, Chrome everywhere).

Probably there is a memory leak and it runs out of memory, but possibly there are other explanations.
I have at least 32GB of RAM everywhere, so maybe memory leak is not THAT plausible.

Steps to reproduce.
1. Go to chess.com/cccc (maybe it's related to ads, so be sure to have ads enabled)
2. Leave it on overnight or just keep open
3. Note it crashed.

**Comment by coolchess123** [comment]
I am closing all issues now, so that we know what new issues to track
