### ISSUE TITLE
Download PGN from Current stage/event

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#24]
Download button for PGN of current round. This should be there, we should not be expected to use a twitch command to find it or go to info box. This is fairly simple to implement

**Comment by chesserik** [comment]
In progress.

**Comment by coolchess123** [comment]
@jak3122 this is really important to be fixed next, can you kindly look into it, all the pgns are listed here, just a download button with link is required https://cccfiles.chess.com/tournamentapi.json
