### ISSUE TITLE
Download PGN from archive

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#25]
Archive is nice, but has same problem. Why does one want archive, to replay games and also get whole round/season pgn's. There is no way to do that in current archive. People have already started complaining to me about this

**Comment by chesserik** [comment]
In progress

**Comment by coolchess123** [comment]
@jak3122 this is really important to be fixed next, can you kindly look into it, all the pgns are listed here, just a download button with link is required https://cccfiles.chess.com/tournamentapi.json
