### ISSUE TITLE
Engine configuration info in boxes

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#26]
This is implemented, but few settings are still wrong, like Threads is 2 for Leealfish on top, but then aux engine threads shows as 1

This is not a show stopped for C9 but its something that must be improved

**Comment by coolchess123** [comment]
Khag I think settings are fixed

If not please update which engine info is wrong

If things are good close the issue please

**Comment by chesserik** [comment]
?

**Comment by coolchess123** [comment]
This will be kept open till we see other engines and how their info pops up
