### ISSUE TITLE
Few games abruptly ending

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#27]
> It could be some infrastructure issue but would be nice to debug as it could happen in c9 also
> 
> Games 10 14 17
> 
> Regards 
> Arun

**Comment by coolchess123** [comment]
Lc0 crash in CCC was because of lack of resources, apparently 3 allie processes were running and it caused the crashes in many games, why the processes were left over, its not figured out yet, but the software has been updated to get rid of lingering engines if any before new game starts, all crashed games are getting replayed
https://i.imgur.com/gSTj2bK.png

**Comment by coolchess123** [comment]
The standings and crosstable does get updated after replayed games, however when we click on the game that was replayed, it still has the old game data.

If that is fixed, we can close the issue

**Comment by chesserik** [comment]
I’ll check on this

**Comment by chesserik** [comment]
Should be done now.
