### ISSUE TITLE
Need a way to copy older position to "Analysis" tab.

### ISSUE THREAD

**Issue by mooskagh** [coolchess123/CCC-feedback#3]
Currently it's only possible to copy the current position into analysis tab.
However the most frequent use case that I find useful is when you expect engine to make some obvious move (capture a hanging piece) and then engine doesn't do that. In this case you need to revert to some older position and check what would happen if that piece was taken.

So, would be nice if copying of previous positions into analysis tab would be supported.

**Comment by coolchess123** [comment]
Will pass it on

**Comment by coolchess123** [comment]
So you need the analysis also on any PV move you select, if i am not wrong. this way you can analyze any move in the move history?

**Comment by coolchess123** [comment]
This cannot be fixed as per the team

**Comment by mooskagh** [comment]
Cannot be fixed?? What's the point of analysis tab without that?
Also, why cannot it be fixed? Is it that hard to add "trim last move" button?
