### ISSUE TITLE
Game 282 not updated in schedule/crosstable

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#33]
It was won by Allie, but not showing up
![image](https://user-images.githubusercontent.com/22060423/58927914-4db7fb00-8705-11e9-8c4f-0ba50787060a.png)

**Comment by coolchess123** [comment]
This kind of issues must be fixed, as this affects standings

**Comment by coolchess123** [comment]
In allie vs LCO first game empty, why it becomes so we need to understand

**Comment by chesserik** [comment]
Game crashed and was replayed. Working on fixing it to remove that empty game.
