### ISSUE TITLE
Schedule & crosstable for DEMO and Testing Updates II empty.

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#34]
Re-open the "DEMO"  or "Testing Updates II" events via the new drop down.  Select "Schedule" ... you will find a blank space.  Select "Standings", and then "View Crosstable" ... you will find engines/scores listed, but no individual game results.  Other events seem OK.  I was unable to make my usual crosstable snapshot (for CCC Discord Tournament Results Channel) because of this bug.

**Comment by Khagrin2** [comment]
Just an update ... The Lc0 vs. Allie 132 game match follows this same pattern, i.e. empty schedule, no crosstable, no match data available.  Viewers like to review results or replay games from prior CCC broadcasts, e.g. to find/share interesting games worthy of analysis or even produce YouTube videos.

**Comment by chesserik** [comment]
Agreed!
