### ISSUE TITLE
DEMO: King's Gambit Game 48 (and several others) "abandoned"

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#35]
Game 48:  Allie played 31. h4 ... in downloaded .pgn game is then marked "abandoned".  Game was scored +1 for Brainfish even though Allie made the last move.
Game 51:  Leelafish (black) played 16. .... g6  then "abandoned".  Scored +1 for Leelafish.
Game 52:  Leelafish (white) played 22. Qh4 then "abandoned".  Scored +1 for Leelafish.
Game 53:  Allie (black) played 15. ... Nf8 then "abandoned".  Scored +1 for Lc0.
Game 54:  Allie (white) played 13. Qf6 then "abandoned".  Scored +1 for Lc0.
Game 59:  Brainfish vs. Allie ... proceeded 20 something moves, graphs weirded out and now game is "gone" from schedule.
Game 60: Allie vs. Brainfish ... same thing as game 59, though there was a "resume" tossed into the mix.
Games 63, 64, 65, 66 ... all more "abandoned" Allie games

**Comment by Khagrin2** [comment]
Note that all of these problematic games are "Allie" games.

**Comment by robertomil81mil** [comment]
Game 63, 64 same thing, games are stoped.
