### ISSUE TITLE
Graphs GUI glitch (pretty bad one, requires refresh at end of each game)

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#38]
I'm not sure when this cropped up.  When a new game starts, the move offsets for the graphs are not correct ... i.e. each graph starts with the first move an engine "thinks" on and they do not include the book moves.  This means you can't easily tell from the graph where the forced line ended.  Worse, clicking on a graph "dot" takes you to the wrong move.  You need to "refresh" to have this problem correct itself.  The snapshot below illustrates the problem.  Note the 17 moves in the move list, but only 5 in the graph (the forced line in this game ended on move 13. ... Be7).

![image](https://user-images.githubusercontent.com/40367843/59242887-734c7500-8bdb-11e9-96cb-d74394db7299.png)

**Comment by Khagrin2** [comment]
Actually, I suspect this is a result of the "fix" for the (now closed) issue regarding the numbers/graphs not displaying at the start of a new game (similarly requiring a "refresh").  The symptoms are closely related.  Note that when a game ends, the graphs "correct themselves" momentarily during the pause until the next game begins.  Similarly, for the prior issue, the graphs/numbers would suddenly appear during that pause.  So, when addressing this issue, please take care to not re-introduce that (even worse) prior problem.  And _please_ verify any fix by watching closely the transition between games since "refreshing" or just loading up the page and watching for a bit would make one think all is well.

**Comment by Khagrin2** [comment]
Update.  Previous comment about graph being correct at the end of a game during the pause.  This is not entirely  correct.  Note the snapshot below.  This is from the WC Replays, game 18.  Note the Kibitzer blue line is not offset correctly.  "Blue" did NOT see the eval change way ahead of Brainfish and Lc0.   I'm now assuming that when you "refresh" and things look correct they are not correct for the "blue line", i.e. _the blue line is always offset improperly with respect to the engine lines_.  So, this bug is even worse that first indicated if you are interested in the Kibitzer.

![image](https://user-images.githubusercontent.com/40367843/59266324-62205a00-8c15-11e9-88e7-1a4d79cbf627.png)

**Comment by coolchess123** [comment]
@Khagrin2 can u confirm this and close it please

**Comment by Khagrin2** [comment]
Appears fixed!
