### ISSUE TITLE
Engine PVs no longer working properly

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#39]
An engine's PV (principal variation) move list is now displayed only _after_ that engine's move is completed, i.e. when it is no longer "thinking".  When an engine is active, viewers can no longer see what moves are being considered.   _Only a single engine's expected line of play can be seen at any given time_.  

Previously both PV move lists were typically displayed (though some engines, e.g. Houdini would sometimes not show such).  

Besides seeing both engine's preferred lines of play, there was the additional benefit that the "blue" moves in the PV move lists indicated the first point of disagreement.  Of course these highlighted moves are now totally pointless.  

Showing only the non-thinking engine's PV has considerably impaired this previously well functioning and useful feature.  Please repair prior to CCC9.

**Comment by chesserik** [comment]
Totally agreed.

**Comment by jak3122** [comment]
Deployed a fix today, how's it look?

**Comment by Khagrin2** [comment]
Looks SUPER :)   I expect this issue can be closed.  I'll watch for a couple of more games, and if nothing unexpected pops up I will close it.  Thanks so much!

**Comment by Khagrin2** [comment]
All looking good!   Working properly.  Both show up nicely for prior game reviews as well (in current event, and in prior events.)  Closing 👍
