### ISSUE TITLE
Stoofvless speed graps.

### ISSUE THREAD

**Issue by robertomil81mil** [coolchess123/CCC-feedback#41]
Where is the Stoofvless NPS? Please fix that, thanks for fix the graps. This is the only issue.
![Screenshot_2019-06-17-10-19-50](https://user-images.githubusercontent.com/51243949/59616319-ccd80680-90e9-11e9-8e09-fc3cb7907498.png)

**Comment by coolchess123** [comment]
Its stoofvles problem
