### ISSUE TITLE
7-man TB coverage question.

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/CCC-feedback#42]
Not an issue, per se ... but there has been considerable discussion in chat regarding whether or not CCC has full 7-man coverage on the CPU box.  The details indicate 14T of RAID for tablebase support on that box.  But in following the issue that arose regarding SF loss to Lc0 (which uncovered a bug in SF), the commenters there indicated that only 621 table base files were detected by SF at startup.  Could a knowledgeable fellow please provide a description that we can use in chat regarding the coverage?  e.g. If only partial it would be nice to know, and "what parts" are used.  If full, that would be great to know as well.  Thanks!

**Comment by Nordlandia** [comment]
Asfaik 7-man EGTB is stored on HDD, per Fire author.

**Comment by coolchess123** [comment]
available in !tb command in twitch
