### ISSUE TITLE
Schedule json

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#64]
For the additional CCC page https://cccinfo.club/

I want to know of some mechanism when a game ends, so that i can download the event pgn and generate my own set of files

Currently i am downloading the pgn itself to check if it has modified, however it becomes too big at the fag end of the tournament

So if there is a schedule json or something that gets generated and can be downloaded using wget, can you please let me know the location

**Comment by jak3122** [comment]
The most lightweight json you can use to check for the end of a game is probably https://cccfiles.chess.com/standings.json which has a `gamesPlayed` field that will increment after each game. The schedule is here if you want it https://cccfiles.chess.com/schedule.json

If you want to avoid polling the json files, you can connect to the websocket at `wss://cccc.chess.com/websocket` and listen for messages with `type: "fullUpdate"`, which have a `res` field when a game has just ended.

**Comment by coolchess123** [comment]
Perfect @jak3122 , the standings json is very small

Thanks a lot

One more request, not urgent, can u send chess.com logo and engine logo in a zip file in mail

**Comment by chesserik** [comment]
I will send you URLs. You do not need assets.
