### ISSUE TITLE
Scrollbar visual broken under FF

### ISSUE THREAD

**Issue by maelic13** [coolchess123/CCC-feedback#7]
In Firefox browser, the scrollbars appear as legacy, default instead of the neat and nice thin black in chrome. It sometimes coveres part of the moves window since they are wider.

**Comment by maelic13** [comment]
![image](https://user-images.githubusercontent.com/30387931/51320422-071c7980-1a60-11e9-8852-57edde0d2527.png)
Just for illustraation - the scroll bar hides parts of the moves. There used to be nice thin black scroll bar under chrome, but it was not there today anymore.

**Comment by coolchess123** [comment]
I am closing all issues now, so that we know what new issues to track
