### ISSUE TITLE
Layout broken today

### ISSUE THREAD

**Issue by hadmir** [coolchess123/CCC-feedback#8]
Broken layout today, all of a sudden, see pic
![chess](https://user-images.githubusercontent.com/19718133/51261418-7aff4900-19b0-11e9-9319-073297b3c166.png)

**Comment by amatrade** [comment]
Same here: MacOS 10.13, Safari, Chrome and Firefox, see screen video (Firefox) on [https://www.dropbox.com/s/0ntoksj0ur2anly/2019-01-16_22-50-28.mp4?dl=0](url)

**Comment by hadmir** [comment]
It is OK again., this can be closed, I guess.

**Comment by amatrade** [comment]
Yes, it's okay again. Thanx!
